import React from "react";
import image_topCount from "../../assets/gmology_benefits_topCount.png";
import image_chronology from "../../assets/gmology_benefits_chronology.png";
import image_chronology2 from "../../assets/gmology_benefits_cronology2.png";
import image_gmologyLogo from "../../assets/logo_color_bg.webp";
import image_likesClaps from "../../assets/gmology_benefits_likesClaps.png";
import image_top10 from "../../assets/gmology_benefits_top10.png";
import logoTwitch from "../../assets/logo_twitch.png";
import iconIGDB from "../../assets/IGDB_logo.png";
import image_barebones from "../../assets/gmology_screenshot_user_colored.png";
import avatar_oneWithTheInternet from "../../assets/avatar_oneWithTheInternet.jpg";
//components
import { Link } from "react-router-dom";
import ReferenceCollections from "../organisms/ReferenceCollections";

function Homepage() {
  return (
    <div className="homepage">
      <section className="notice">
        <div className="notice__text">
          <p>
            <strong>Notice:</strong> gmology.com is in beta stage. Feel free to
            send your feedback to OneWithTheInternet@gmail.com. Full release:
            07/01/23.*
          </p>
        </div>
      </section>

      {/* <section className="giveawayNotice">
        <div className="giveawayNotice__text">
          <Link to={"giveaway"}>Learn about current giveaway</Link>
        </div>
      </section> */}

      <section className="headline">
        <div className="headline__background">
          <div className="headline__background--purple">
            <div className="headline__background--black">
              <div className="headline__logo">
                <div>
                  <img src={image_gmologyLogo} alt="gmology logo" />
                </div>
              </div>

              <div className="headline__title">
                <div>
                  <h1>SAVE AND SHARE YOUR GAMING HISTORY</h1>
                </div>
              </div>

              <div className="startNow__signUp">
                <Link to={"signup"}>
                  <input
                    className="homepagesignUpButton"
                    type={"button"}
                    value={"Start Now"}
                  ></input>
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className="productDetails">
        <div className="productDetails__whatIsIt">
          <div className="productDetails__whatIsIt__title">
            <h3>What Is Gmology</h3>
          </div>
          <div className="productDetails__whatIsIt__decription">
            <p>
              Create an online <strong>inventory</strong> of all the{" "}
              <strong> games you've played </strong> or owned. Be part of the
              free indie <strong> social </strong> platform for longtime video{" "}
              <strong>game lovers</strong>.
            </p>
          </div>
        </div>

        <div className="productDetails__howItWorks">
          <div className="productDetails__howItWorks__title">
            <h3>How it Works</h3>
          </div>
          <div className="productDetails__howItWorks__video">
            <iframe
              width="560"
              height="315"
              src="https://www.youtube.com/embed/hbB3cI1AUsI"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowFullScreen
            ></iframe>
          </div>
        </div>
      </section>

      <ReferenceCollections />

      <section className="benefits">
        <div className="benefits__chronology">
          <img src={image_chronology} alt={"benefit illustration"} />
          <h2>Discover your Chronology</h2>
          <h4>(aka a gmology)</h4>
          <p>
            See where your gaming journey has taken you in a{" "}
            <strong> beautiful, neat and tidy</strong> autogenerated chronology
            and watch it grow as you grow.
          </p>
        </div>

        <div className="benefits__top10">
          <img src={image_top10} alt={"benefit illustration"} />
          <h2>Show Your Top 10</h2>
          <p>
            You want your favorite games set in Internet stone or your followers
            to know your passions in a nutshell, Gmology's got you.
          </p>
        </div>

        <div className="benefits__chronology2">
          <img src={image_chronology2} alt={"Chonology screenshot"} />
          <h2>Hoard without hoarding</h2>
          <p>
            Want to own all those <strong>games that left a mark on you</strong>
            , but that's just way too many? Add them to your gmology to feel
            that same sense of accomplishment.
          </p>
        </div>

        <div className="benefits__barebones">
          <img src={image_barebones} alt={"benefit illustration"} />
          <h2>Barebones Approach</h2>
          <p>
            Unlike other sites, Gmology is clean and simple. It's just about
            you, your top 10 and your chronology.
          </p>
        </div>

        <div className="benefits__topCount">
          <img src={image_topCount} alt={"benefit illustration"} />
          <h2>Top1 Counter</h2>
          <p>
            See how many more people agree that your top #1 game is the absolute
            best of all time.
          </p>
        </div>

        <div className="benefits__likesClaps">
          <img src={image_likesClaps} alt={"benefit illustration"} />
          <h2>Claps and Likes</h2>
          <p>
            Send your favorite gamer some love by liking or clapping to their
            gmology. <strong>Clapping doesn't require an account.</strong>
          </p>
        </div>
      </section>

      <section className="poweredBy">
        <div>
          <h2>In Association With</h2>
        </div>
        <div className="poweredBy__icons">
          <img src={logoTwitch} alt={"igdb logo"} />
          <img src={iconIGDB} alt={"igdb logo"} />
        </div>
        <div>
          <p>
            Building a Gmology is no small task. Relax, Gmology's insanely
            powerful videogame database is provided and maintained by the good
            people at Twitch and IGDB, so your collection isn't going anywhere.
          </p>
        </div>
      </section>

      <section className="startNow">
        <div className="startNow__signUp">
          <Link to={"signup"}>
            <input
              className="homepagesignUpButton"
              type={"button"}
              value={"Start Now"}
            ></input>
          </Link>
        </div>
      </section>

      <section className="footNotes">
        <p>*Full release planned for 07/01/23.</p>
      </section>
    </div>
  );
}

export default Homepage;
